apiVersion: v2
name: tezos-chain
description: A Helm chart for Tezos nodes on Kubernetes
type: application
version: 4.0.0
appVersin: 1.0b1
keywords:
  - tezos
  - blockchain
home: https://github.com/tqtezos/tezos-k8s
dependencies:
  - name: authenticated-rpc-tezos-chain
    repository: file://../rpc-auth
    version: 0.1.0
    condition: rpc_auth
