baker: true
baker_command: tezos-baker-007-PsDELPH1
chain_name: YOUR_CHAIN_NAME_HERE
is_invitation: false
rpc_auth: false
zerotier_in_use: false
zerotier_config:
  zerotier_network: YOUR_NETWORK_ID_HERE
  zerotier_token: YOUR_ZEROTIER_TOKEN_HERE
containers:
  zerotier: "tqtezos/tezos-k8s-zerotier:1.2.3"
  # rpc-auth: "tqtezos/tezos-k8s-rpc-auth:1.0b1"
  tezos: tezos/tezos:v7-release
protocol:
  bootstrap_mutez: "4000000000000"
  hash: PsDELPH1Kxsxt8f9eWbxQeRxkjfbxoqM52jvs5Y5fBxWWh4ifpo
genesis:
  genesis_chain_id: "YOUR_GENESIS_CHAIN_ID_HERE"
  bootstrap_timestamp: "YOUR_BOOTSTRAP_TIMESTAMP_HERE"
accounts:
  - name: sample1
    key: !!binary |
      WldSd2EzWk1jR1psUVZNNU5EUmpSRGRXT0hVelRFaHdVR0oxVVZaUlVYVjRZVzFOYmxGR1dubG5T
      RkZhZFZKUmVHSklPVFU0
    private: true
    bootstrap: true
    baker: true
  - name: sample2
    key: !!binary |
      SAMPLE==
    private: true
    bootstrap: true
nodes:
  - bake_for: baker
# TODO
# archive nodes, node with open rpc
# take into account fundraisers accounts that people need to activate
